---
- name: Cacao Bad Dog Pew
  hosts: all
  sudo: yes

  roles:
    # Prerequisites
    - docker
    - docker-py
    - drupal-scripts

    # Option sample data
    - role: sample-config
      when: sample_config is defined and sample_config == True
    - role: sample-databases
      when: sample_databases is defined and sample_databases == True

    # Determine what the school codes are by looking at the contents of
    # src/config.
    - school-get-ids

    # Docker containers
    - drupal-databases
    - school-code
    - drupal-php
    - drupal-install
    - drupal-server
