---
- name: Cacao Bad Dog Pew
  hosts: all
  sudo: yes

  roles:
    # Prerequisites
    - docker
    - docker-py
    - drupal-scripts

    # Determine what the local school codes are by looking at the contents of
    # src/config.
    - school-get-local-ids

    # Docker containers
    - drupal-databases
    - school-code
    - school-config
    - drupal-php
    - drupal-install
    - drupal-server
